export const initialIncidents = [
    {
        id: 1,
        title: 'Biased Recommendation Algorithm',
        description: 'Algorithm consistently favored certain demographics...',
        severity: 'Medium',
        reported_at: '2025-03-15T10:00:00Z',
      },
      {
        id: 2,
        title: 'LLM Hallucination in Critical Info',
        description: 'LLM provided incorrect safety procedure information...',
        severity: 'High',
        reported_at: '2025-04-01T14:30:00Z',
      },
      {
        id: 3,
        title: 'Minor Data Leak via Chatbot',
        description: 'Chatbot inadvertently exposed non-sensitive user metadata...',
        severity: 'Low',
        reported_at: '2025-03-20T09:15:00Z',
      },
      {
        id: 4,
        title: 'Autonomous Vehicle Collision',
        description: 'Self-driving car failed to detect a pedestrian in a crosswalk...',
        severity: 'High',
        reported_at: '2025-04-05T16:00:00Z',
      },
      {
        id: 5,
        title: 'AI-Generated Fake News Distribution',
        description: 'AI generated and spread fake news during an election campaign...',
        severity: 'High',
        reported_at: '2025-04-07T10:30:00Z',
      },
      {
        id: 6,
        title: 'Unintended Bias in Loan Approval Algorithm',
        description: 'Loan approval system inadvertently discriminated based on gender...',
        severity: 'Medium',
        reported_at: '2025-04-10T12:00:00Z',
      },
      {
        id: 7,
        title: 'Facial Recognition Privacy Breach',
        description: 'Facial recognition technology captured and stored data without consent...',
        severity: 'High',
        reported_at: '2025-04-12T09:00:00Z',
      },
      {
        id: 8,
        title: 'AI-Powered Surveillance Malfunction',
        description: 'Surveillance system incorrectly flagged individuals as threats...',
        severity: 'Medium',
        reported_at: '2025-04-14T13:45:00Z',
      },
      {
        id: 9,
        title: 'AI Chatbot Offensive Responses',
        description: 'Customer support AI chatbot provided inappropriate responses...',
        severity: 'Low',
        reported_at: '2025-04-16T08:00:00Z',
      },
      {
        id: 10,
        title: 'Data Privacy Violation via IoT Devices',
        description: 'IoT devices collected user data without proper encryption...',
        severity: 'High',
        reported_at: '2025-04-18T11:30:00Z',
      },
  ];